name: Ruby

on:
  push:
    branches:
      - main
      - ci

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }} ActiveSupport ${{ matrix.activesupport }}
    strategy:
      matrix:
        ruby:
          - 3.1
          - 3.2
          - 3.3
        activesupport:
          - 5.2.8
          - 6.0.6
          - 6.1.7
          - 7.0.8
          - 7.1.3

    env:
      RUBY_VERSION: ${{ matrix.ruby }}
      ACTIVE_SUPPORT_VERSION: ${{ matrix.activesupport }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run the default task
      run: bundle exec rake
